"""Frozen copy of model.py as it stood through v1-v4 (last commit
10d9caf, before v5's residual-correction redesign) — kept so old
checkpoints (v1/v3/v4) stay loadable and analyzable by
eval_compare/*.py, which historically supported all of them via
constructor overrides (channels/num_blocks/num_planes/
num_phase_buckets) and, for v1 only, a monkeypatched ResidualBlock
(v1 predates the SqueezeExcitation gate added in commit 07f70bb).

Do NOT edit this file to track new architecture ideas — that's what
model.py is for. This one only exists to keep old checkpoints
loadable; update it only if a *loading* bug is found here.

Construction per version:

    # v1 (no SE block -- monkeypatch ResidualBlock first)
    import torch.nn as nn, torch.nn.functional as F
    import legacy_model
    class ResidualBlockV1(nn.Module):
        def __init__(self, channels):
            super().__init__()
            self.conv1 = nn.Conv2d(channels, channels, 3, padding=1, bias=False)
            self.bn1 = nn.BatchNorm2d(channels)
            self.conv2 = nn.Conv2d(channels, channels, 3, padding=1, bias=False)
            self.bn2 = nn.BatchNorm2d(channels)
        def forward(self, x):
            r = x
            out = F.relu(self.bn1(self.conv1(x)))
            out = self.bn2(self.conv2(out))
            return F.relu(out + r)
    legacy_model.ResidualBlock = ResidualBlockV1
    model = legacy_model.ChessCNN(channels=96, num_blocks=8, num_planes=19, num_phase_buckets=4)

    # v3 (SE block present, 31 planes, 8 buckets)
    model = legacy_model.ChessCNN(channels=160, num_blocks=14, num_planes=31, num_phase_buckets=8)

    # v4 (SE block present, 33 planes, 8 buckets -- same as this file's defaults)
    model = legacy_model.ChessCNN()

All versions here use the OLD 2-argument forward(planes, piece_count)
and the OLD PSQTHead skip — see model.py for the current v5 interface
(forward(planes, piece_count, nnue_logit), no PSQT head).
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

NUM_PLANES = 33
BOARD_SIZE = 8
NUM_PIECE_PLANES = 12

PHASE_BUCKET_BOUNDARIES = (26, 22, 18, 14, 10, 6, 3)
NUM_PHASE_BUCKETS = len(PHASE_BUCKET_BOUNDARIES) + 1


def phase_bucket_for_piece_count(piece_count: torch.Tensor) -> torch.Tensor:
    bucket = torch.zeros_like(piece_count)
    for boundary in PHASE_BUCKET_BOUNDARIES:
        bucket += (piece_count < boundary).to(bucket.dtype)
    return bucket


class SqueezeExcitation(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        reduced = max(channels // reduction, 1)
        self.fc1 = nn.Linear(channels, reduced)
        self.fc2 = nn.Linear(reduced, channels)

    def forward(self, x):
        pooled = x.mean(dim=(2, 3))
        gate = torch.sigmoid(self.fc2(F.relu(self.fc1(pooled))))
        return x * gate.unsqueeze(-1).unsqueeze(-1)


class ResidualBlock(nn.Module):
    """SE-gated version -- correct for v3/v4 checkpoints. For v1
    (predates SE), monkeypatch this name before instantiating
    ChessCNN -- see this module's docstring."""

    def __init__(self, channels):
        super().__init__()
        self.conv1 = nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(channels)
        self.conv2 = nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(channels)
        self.se = SqueezeExcitation(channels)

    def forward(self, x):
        residual = x
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        out = self.se(out)
        return F.relu(out + residual)


class PhaseValueHead(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.fc1 = nn.Linear(channels * 2, channels)
        self.fc2 = nn.Linear(channels, 1)

    def forward(self, pooled_mid, pooled_final):
        h = F.relu(self.fc1(torch.cat([pooled_mid, pooled_final], dim=-1)))
        return self.fc2(h).squeeze(-1)


class PSQTHead(nn.Module):
    def __init__(self, num_piece_planes=NUM_PIECE_PLANES, num_phase_buckets=NUM_PHASE_BUCKETS):
        super().__init__()
        self.conv = nn.Conv2d(num_piece_planes, num_phase_buckets, kernel_size=1, bias=False)

    def forward(self, piece_planes, bucket):
        per_bucket = self.conv(piece_planes).sum(dim=(2, 3))
        return per_bucket.gather(1, bucket.unsqueeze(1)).squeeze(1)


class ChessCNN(nn.Module):
    def __init__(self, channels=224, num_blocks=20, num_planes=NUM_PLANES,
                 num_phase_buckets=NUM_PHASE_BUCKETS):
        super().__init__()
        self.stem_conv = nn.Conv2d(num_planes, channels, kernel_size=3, padding=1, bias=False)
        self.stem_bn = nn.BatchNorm2d(channels)

        self.blocks = nn.ModuleList(ResidualBlock(channels) for _ in range(num_blocks))
        self.heads = nn.ModuleList(PhaseValueHead(channels) for _ in range(num_phase_buckets))
        self.psqt = PSQTHead(num_phase_buckets=num_phase_buckets)

    def forward(self, planes, piece_count):
        bucket = phase_bucket_for_piece_count(piece_count)

        x = F.relu(self.stem_bn(self.stem_conv(planes)))
        mid_point = len(self.blocks) // 2
        for i, block in enumerate(self.blocks):
            x = block(x)
            if i == mid_point - 1:
                pooled_mid = x.mean(dim=(2, 3))

        pooled_final = x.mean(dim=(2, 3))

        trunk_logits = torch.empty(planes.shape[0], device=planes.device, dtype=pooled_final.dtype)
        for bucket_idx, head in enumerate(self.heads):
            mask = bucket == bucket_idx
            if mask.any():
                trunk_logits[mask] = head(pooled_mid[mask], pooled_final[mask])

        psqt_logits = self.psqt(planes[:, :NUM_PIECE_PLANES], bucket)
        return trunk_logits + psqt_logits

    @torch.no_grad()
    def eval_centipawns(self, planes, piece_count, cp_scale=410.0):
        logit = self.forward(planes, piece_count)
        return cp_scale * logit
